# Numpy Questions

### Q.1) Create a numpy array in python?

In [10]:
import numpy as np

arr1d = np.array([1,2,3,4,5])
print(arr1d)
print(arr1d.shape)

[1 2 3 4 5]
(5,)


In [11]:
arr2d = np.array([[1,2,3], [4,5,6]])
print("\n2d array: ",arr2d)
arr2d.shape


2d array:  [[1 2 3]
 [4 5 6]]


(2, 3)

### Q.2) Write a program that takes in a NumPy array and returns its mean?

In [12]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(np.mean(arr))

3.0


In [ ]:
import numpy as np

def calculate_mean(arr):
    mean = np.mean(arr)
    return mean

# Example usage
arr = np.array([1, 2, 3, 4, 5])
result = calculate_mean(arr)
print("Mean:", result)


### Q.3) Write a program that takes in a NumPy array and returns its shape?

In [13]:
arr2d = np.array([[1,2,3], [4,5,6]])
print("\n2d array: ",arr2d)
arr2d.shape


2d array:  [[1 2 3]
 [4 5 6]]


(2, 3)

In [ ]:
import numpy as np

def get_array_shape(arr):
    shape = arr.shape
    return shape

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = get_array_shape(arr)
print("Shape:", result)


### Q.4) How can we convert a list into numpy array?

In [14]:
import numpy as np

list1 = [1,2,3,4,5]
arr = np.array(list1)
arr

array([1, 2, 3, 4, 5])

### Q.5) Creates a NumPy array filled with zeros of 3X3 size?

In [15]:
import numpy as np

arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Q.6)  Creates a NumPy array filled with ones of mXn size?

In [20]:
import numpy as np
import random

m = random.randint(1, 5)
n = random.randint(1, 5)

arr = np.ones((m, n))
print(arr)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


### Q.7) Creates a NumPy array filled with random values between 0 and 1.

In [22]:
import numpy as np

arr = np.random.random((3,3))
arr

array([[0.96483776, 0.19375165, 0.91553456],
       [0.96819506, 0.02741599, 0.36472066],
       [0.95284855, 0.64765938, 0.69130604]])

### Q.8)  Creates a NumPy array with a range of values?

In [23]:
import numpy as np

arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Q.9) How to reshape a NumPy array to a new shape?

In [29]:
import numpy as np

arr = np.arange(1,10)
print(arr)
arr1 = arr.reshape((3,3))
arr1

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Q.10) Computes the sum of all the elements in a NumPy array?

In [32]:
import numpy as np

arr = np.arange(1,10)
arr_sum = np.sum(arr)

arr_sum

45

### Q.11) Computes the standard deviation of all the elements in a NumPy array.

In [33]:
import numpy as np

arr = np.arange(1,10)
arr_std = np.std(arr)

arr_std

2.581988897471611

### Q.12) Computes the dot product of two NumPy arrays.


In [41]:
import numpy as np

arr1 = np.arange(1,4)
arr2 = np.arange(4,7)

#dot product is a mathematical operation that multiplies corresponding elements from both arrays and sums them up
dot_product1 = np.dot(arr1, arr2)

dot_product1 = arr1 @ arr2  #uses the @ operator, known as the matrix multiplication operator

print("Dot product using np.dot():", dot_product1)
print("Dot product using @ operator:", dot_product2)

Dot product using np.dot(): 32
Dot product using @ operator: 32


### Q.13) Create a 2D NumPy array with shape (3, 3) containing all zeros?

In [44]:
import numpy as np

arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q.14) Create a 1D numpy array containing the values from -10 to 10, with a step of 2.


In [45]:
import numpy as np

arr = np.arange(-10,10,2)
arr

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

### Q.15) Create a 2D numpy array with shape (3, 3) containing random values between 0 and 1. Then, set all values in the first row to 0.

In [48]:
import numpy as np 

arr = np.random.random((3,3))
print(arr)
arr[0, :] = 0
arr

[[0.62982476 0.83582728 0.45819433]
 [0.61574372 0.62990771 0.05504854]
 [0.50209845 0.55812662 0.94115781]]


array([[0.        , 0.        , 0.        ],
       [0.61574372, 0.62990771, 0.05504854],
       [0.50209845, 0.55812662, 0.94115781]])

### Q.16) Create a 1D numpy array containing the values from 0 to 9. Then, create a new array containing the values squared.

In [51]:
import numpy as np

arr = np.arange(10)
print(arr)
arr1 = arr**2
arr1

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

### Q.17) Create a 1D numpy array containing the values from 1 to 10. Then, extract all even values from the array.

In [55]:
import numpy as np

arr = np.arange(1,11)
print(arr)

print("Even values:", arr[arr%2==0])

[ 1  2  3  4  5  6  7  8  9 10]
Even values: [ 2  4  6  8 10]


### Q.18) Create a 1D numpy array containing the values from 1 to 10. Then, extract all odd values from the array.

In [56]:
import numpy as np

arr = np.arange(1,11)
print(arr)

print("Even values:", arr[arr%2 != 0])

[ 1  2  3  4  5  6  7  8  9 10]
Even values: [1 3 5 7 9]


### Q.19)Create a 2D numpy array with shape (3, 3) containing random values between 0 and 1. Then, compute the mean of each row.

In [58]:
import numpy as np 

arr = np.random.random((3,3))
print(arr)
rows_mean = np.mean(arr, axis=1)
rows_mean

[[0.64976822 0.78409224 0.73319235]
 [0.54779628 0.47154622 0.58484417]
 [0.23364857 0.07032538 0.0131845 ]]


array([0.72235094, 0.53472889, 0.10571948])

### Q.20) How to split numpy array into 3 parts?
#### arr = np.array([1, 2, 3, 4, 5, 6])

In [67]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

split_arr = np.split(arr,3)
print(split_arr)

for part in split_arr:
    print(part)

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]
